// ==================== PART 4: ADVANCED MATERIAL MANUFACTURERS ====================
// These companies take processed metals and create specialized battery materials,
// semiconductor materials, display materials, and other high-tech components

// Create indexes
CREATE INDEX material_mfg_id IF NOT EXISTS FOR (m:MaterialMfg) ON (m.id);

// ==================== CATHODE MATERIAL MANUFACTURERS ====================
// Produce NMC, NCA, LFP cathode materials for lithium-ion batteries

CREATE
// China - CATL Material Division
(mat_cathode_catl:MaterialMfg {
  id: 'MAT-CATH-CATL',
  name: 'CATL Cathode Materials',
  parent_company: 'Contemporary Amperex Technology Co. Limited (CATL)',
  country: 'China',
  region: 'Fujian Province',
  coordinates: [25.4333, 119.0167],
  material_type: 'Cathode Active Materials',
  products: ['NMC 811', 'NMC 622', 'NMC 523', 'LFP', 'LMFP'],
  nmc811_capacity_tonnes_year: 85000,
  nmc622_capacity_tonnes_year: 45000,
  lfp_capacity_tonnes_year: 120000,
  total_capacity_tonnes_year: 250000,
  output_purity_percent: 99.9,
  operating_since: 2011,
  workforce: 4200,
  technology: 'Co-precipitation + sintering',
  nmc_nickel_content_percent: 80,
  nmc_cobalt_content_percent: 10,
  nmc_manganese_content_percent: 10,
  energy_density_wh_kg: 720,
  cycle_life: 2000,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001'],
  customer_base: ['CATL (internal)', 'BYD', 'EVE Energy', 'CALB'],
  market_position: 'World\'s largest cathode producer',
  r_and_d_investment_usd_million_year: 180,
  patents: 456,
  vertical_integration: true,
  next_gen_development: ['Sodium-ion cathodes', 'Solid-state cathodes', 'Cobalt-free NMX'],
  environmental_rating: 'B+',
  recycling_program: true,
  recycled_content_percent: 12
}),

// South Korea - L&F (LG Energy Solution supplier)
(mat_cathode_lnf:MaterialMfg {
  id: 'MAT-CATH-LNF',
  name: 'L&F Materials',
  country: 'South Korea',
  region: 'Ochang, North Chungcheong',
  coordinates: [36.7167, 127.4500],
  material_type: 'Cathode Active Materials',
  products: ['NCMA', 'NCA', 'NMC 712', 'NMC 622'],
  specialty: 'High-nickel cathodes',
  ncma_capacity_tonnes_year: 42000,
  nca_capacity_tonnes_year: 35000,
  total_capacity_tonnes_year: 95000,
  operating_since: 2001,
  workforce: 1850,
  technology: 'Advanced co-precipitation',
  nickel_content_range_percent: '70-90',
  energy_density_wh_kg: 750,
  thermal_stability: 'Enhanced',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  exclusive_supplier: 'LG Energy Solution (majority)',
  customer_approvals: ['Tesla', 'GM', 'Hyundai', 'Ford'],
  quality_rating: 'Premium',
  defect_rate_ppm: 5,
  r_and_d_staff: 280,
  patents: 312,
  pilot_production_facility: true,
  custom_formulation_capability: true,
  environmental_rating: 'A-',
  carbon_neutral_target_year: 2030,
  renewable_energy_percent: 35
}),

// Japan - Sumitomo Metal Mining (NCA specialist)
(mat_cathode_sumitomo:MaterialMfg {
  id: 'MAT-CATH-SUM',
  name: 'Sumitomo Metal Mining Cathode Division',
  country: 'Japan',
  region: 'Niihama, Ehime',
  coordinates: [33.9600, 133.3167],
  material_type: 'Cathode Active Materials',
  products: ['NCA', 'NMC 811', 'High-voltage spinel'],
  specialty: 'NCA for Panasonic/Tesla',
  nca_capacity_tonnes_year: 28000,
  total_capacity_tonnes_year: 45000,
  operating_since: 1997,
  workforce: 980,
  technology: 'Proprietary hydroxide co-precipitation',
  nca_nickel_content_percent: 80,
  nca_cobalt_content_percent: 15,
  nca_aluminum_content_percent: 5,
  energy_density_wh_kg: 720,
  cycle_life: 2500,
  quality_control: 'Industry leading',
  defect_rate_ppm: 2,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  strategic_customer: 'Panasonic (Tesla partnership)',
  long_term_contracts: true,
  vertical_integration: 'Upstream nickel/cobalt refining',
  environmental_rating: 'A',
  zero_waste_to_landfill: true,
  responsible_minerals_initiative: true,
  traceability: 'Full supply chain visibility'
}),

// China - GEM (recycling leader)
(mat_cathode_gem:MaterialMfg {
  id: 'MAT-CATH-GEM',
  name: 'GEM Co. Ltd Cathode Materials',
  country: 'China',
  region: 'Jingmen, Hubei',
  coordinates: [31.0333, 112.2000],
  material_type: 'Cathode Active Materials',
  products: ['NMC 811', 'NMC 622', 'NCA'],
  specialty: 'Recycled battery materials',
  total_capacity_tonnes_year: 120000,
  recycled_content_capacity_tonnes_year: 50000,
  operating_since: 2001,
  workforce: 3500,
  technology: 'Urban mining + hydrometallurgy',
  recycling_capability: true,
  battery_recycling_capacity_tonnes_year: 120000,
  recovery_rate_percent: 98.5,
  circular_economy_model: true,
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['CATL', 'Samsung SDI', 'SK On', 'LG Energy Solution'],
  strategic_partnerships: ['Volkswagen recycling', 'Toyota battery recycling'],
  environmental_rating: 'A',
  carbon_footprint_reduction_percent: 60,
  sustainability_awards: ['China Green Company Award', 'UN Global Compact'],
  innovation: 'Battery passport implementation',
  traceability_platform: 'Blockchain-based'
}),

// Belgium - Umicore Rechargeable Battery Materials
(mat_cathode_umicore:MaterialMfg {
  id: 'MAT-CATH-UMI',
  name: 'Umicore Rechargeable Battery Materials',
  country: 'Belgium',
  region: 'Olen',
  coordinates: [51.1500, 4.9167],
  material_type: 'Cathode Active Materials',
  products: ['NMC', 'NCA', 'Custom formulations'],
  specialty: 'High-performance custom cathodes',
  total_capacity_tonnes_year: 75000,
  operating_since: 2006,
  workforce: 1200,
  technology: 'Proprietary co-precipitation',
  customization_capability: true,
  r_and_d_excellence: true,
  r_and_d_staff: 320,
  patents: 580,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001', 'RBA'],
  customer_base: ['European OEMs', 'Samsung SDI', 'SK On'],
  ethical_sourcing: 'Industry leader',
  conflict_free_certification: true,
  full_traceability: true,
  closed_loop_recycling: true,
  recycling_efficiency_percent: 95,
  environmental_rating: 'A+',
  carbon_neutral: true,
  renewable_energy_percent: 100,
  sustainability_leadership: 'Top rated globally',
  expansion_plans: ['Poland facility', 'Canada facility'],
  strategic_importance: 'European battery independence'
});

// ==================== ANODE MATERIAL MANUFACTURERS ====================
// Produce graphite, silicon-graphite, and other anode materials

CREATE
// China - BTR New Energy Materials
(mat_anode_btr:MaterialMfg {
  id: 'MAT-ANODE-BTR',
  name: 'BTR New Energy Materials',
  country: 'China',
  region: 'Shenzhen, Guangdong',
  coordinates: [22.5431, 114.0579],
  material_type: 'Anode Active Materials',
  products: ['Artificial graphite', 'Natural graphite', 'Silicon-graphite composite', 'Hard carbon'],
  artificial_graphite_capacity_tonnes_year: 120000,
  natural_graphite_capacity_tonnes_year: 45000,
  silicon_composite_capacity_tonnes_year: 8000,
  total_capacity_tonnes_year: 173000,
  operating_since: 2002,
  workforce: 3800,
  technology: 'High-temperature graphitization',
  graphitization_temp_celsius: 3000,
  particle_size_control: 'Precision D50 control',
  coating_technology: 'Proprietary surface treatment',
  capacity_mah_g: 365,
  first_cycle_efficiency_percent: 94.5,
  cycle_life: 5000,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001'],
  customer_base: ['CATL', 'BYD', 'LG Energy Solution', 'Samsung SDI'],
  market_position: 'World\'s largest anode material producer',
  r_and_d_investment_usd_million_year: 95,
  silicon_anode_development: 'Next-gen 450mAh/g',
  environmental_rating: 'B',
  energy_consumption_kwh_kg: 15
}),

// Japan - Hitachi Chemical (now Showa Denko)
(mat_anode_hitachi:MaterialMfg {
  id: 'MAT-ANODE-HIT',
  name: 'Showa Denko Materials (formerly Hitachi Chemical)',
  country: 'Japan',
  region: 'Ibaraki',
  coordinates: [36.2000, 140.1167],
  material_type: 'Anode Active Materials',
  products: ['MAGE (Micro-Anode Graphite for high Energy)', 'Silicon-oxide composite'],
  specialty: 'High-capacity silicon anodes',
  total_capacity_tonnes_year: 28000,
  operating_since: 1999,
  workforce: 680,
  technology: 'Advanced silicon coating',
  capacity_mah_g: 420,
  silicon_content_percent: 15,
  volume_expansion_control: 'Enhanced stability',
  first_cycle_efficiency_percent: 91,
  cycle_life: 3000,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Panasonic', 'Nissan', 'Honda'],
  quality_rating: 'Premium',
  r_and_d_excellence: true,
  patents: 245,
  next_gen_target: '500mAh/g by 2026',
  environmental_rating: 'A-'
}),

// South Korea - POSCO Chemical
(mat_anode_posco:MaterialMfg {
  id: 'MAT-ANODE-POS',
  name: 'POSCO Chemical Anode Materials',
  country: 'South Korea',
  region: 'Gwangyang',
  coordinates: [34.9408, 127.6958],
  material_type: 'Anode Active Materials',
  products: ['Artificial graphite', 'Natural graphite', 'Silicon-carbon composite'],
  total_capacity_tonnes_year: 85000,
  expansion_capacity_2025_tonnes_year: 140000,
  operating_since: 2010,
  workforce: 1450,
  technology: 'Integrated graphite processing',
  vertical_integration: 'Graphite mining to finished anode',
  graphite_mines: 'Argentina lithium + graphite projects',
  capacity_mah_g: 360,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['LG Energy Solution', 'SK On', 'Samsung SDI'],
  strategic_partnerships: ['GM Ultium', 'Hyundai Motor'],
  expansion_plans: ['South Korea expansion', 'US facility planned'],
  environmental_rating: 'A-',
  renewable_energy_percent: 28
});

// ==================== ELECTROLYTE MANUFACTURERS ====================
// Produce lithium salts and electrolyte solutions

CREATE
// China - Guangzhou Tinci Materials
(mat_electrolyte_tinci:MaterialMfg {
  id: 'MAT-ELEC-TIN',
  name: 'Guangzhou Tinci Materials Technology',
  country: 'China',
  region: 'Guangzhou, Guangdong',
  coordinates: [23.1291, 113.2644],
  material_type: 'Electrolyte Solutions',
  products: ['LiPF6 lithium salt', 'Electrolyte solvents', 'Electrolyte additives', 'Complete electrolyte formulations'],
  lipf6_capacity_tonnes_year: 55000,
  electrolyte_solution_capacity_tonnes_year: 180000,
  total_capacity_tonnes_year: 235000,
  operating_since: 1996,
  workforce: 2800,
  technology: 'Continuous production process',
  purity_lipf6_percent: 99.99,
  moisture_content_ppm: '<20',
  hf_content_ppm: '<50',
  formulation_expertise: 'Custom blends for different chemistries',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001'],
  customer_base: ['CATL', 'BYD', 'LG Energy Solution', 'Samsung SDI', 'Panasonic'],
  market_position: 'World\'s largest electrolyte producer',
  market_share_percent: 32,
  r_and_d_investment_usd_million_year: 85,
  patents: 520,
  solid_state_electrolyte_development: true,
  environmental_rating: 'B+',
  safety_certifications: ['ISO 45001', 'Chemical safety audits']
}),

// Japan - Mitsubishi Chemical
(mat_electrolyte_mitsubishi:MaterialMfg {
  id: 'MAT-ELEC-MIT',
  name: 'Mitsubishi Chemical Electrolyte Division',
  country: 'Japan',
  region: 'Yokkaichi, Mie',
  coordinates: [34.9667, 136.6250],
  material_type: 'Electrolyte Solutions & Additives',
  products: ['High-purity LiPF6', 'Advanced additives', 'High-voltage electrolytes'],
  specialty: 'Premium quality for demanding applications',
  total_capacity_tonnes_year: 45000,
  operating_since: 1994,
  workforce: 780,
  technology: 'Ultra-high purity synthesis',
  purity_lipf6_percent: 99.995,
  quality_control: 'Pharmaceutical-grade processes',
  defect_rate_ppm: 1,
  high_voltage_capability: 'Up to 4.5V',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Panasonic', 'Toyota', 'Honda', 'Samsung SDI'],
  premium_pricing: true,
  r_and_d_excellence: true,
  patents: 380,
  next_gen_development: ['Solid electrolytes', 'Fluorinated solvents'],
  environmental_rating: 'A',
  safety_record: 'Industry leading'
}),

// South Korea - Enchem
(mat_electrolyte_enchem:MaterialMfg {
  id: 'MAT-ELEC-ENC',
  name: 'Enchem Co. Ltd',
  country: 'South Korea',
  region: 'Ansan, Gyeonggi',
  coordinates: [37.3219, 126.8308],
  material_type: 'Electrolyte Solutions',
  products: ['Electrolyte solutions', 'Functional additives'],
  total_capacity_tonnes_year: 68000,
  operating_since: 1999,
  workforce: 920,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['LG Energy Solution', 'SK On', 'Samsung SDI'],
  strategic_partnerships: 'Long-term supply agreements',
  quality_rating: 'High',
  environmental_rating: 'A-'
});

// ==================== SEPARATOR MANUFACTURERS ====================
// Produce microporous polymer membranes for battery safety

CREATE
// China - Senior Technology Material
(mat_separator_senior:MaterialMfg {
  id: 'MAT-SEP-SEN',
  name: 'Senior Technology Material Co.',
  country: 'China',
  region: 'Foshan, Guangdong',
  coordinates: [23.0219, 113.1219],
  material_type: 'Battery Separators',
  products: ['Wet-process PE separator', 'Dry-process PP separator', 'Ceramic-coated separator'],
  production_method: ['Wet process (phase inversion)', 'Dry process (stretching)'],
  capacity_million_sqm_year: 1800,
  thickness_um: 9,
  porosity_percent: 42,
  shutdown_temperature_celsius: 135,
  meltdown_temperature_celsius: 165,
  ceramic_coating: 'Al2O3',
  coating_thickness_um: 2,
  operating_since: 2005,
  workforce: 2600,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001'],
  customer_base: ['CATL', 'BYD', 'EVE Energy', 'LG Energy Solution'],
  market_position: 'One of top 3 globally',
  r_and_d_investment_usd_million_year: 42,
  environmental_rating: 'B+',
  quality_consistency: 'High'
}),

// Japan - Asahi Kasei
(mat_separator_asahi:MaterialMfg {
  id: 'MAT-SEP-ASA',
  name: 'Asahi Kasei Hipore',
  country: 'Japan',
  region: 'Moriyama, Shiga',
  coordinates: [35.0667, 135.9833],
  material_type: 'Battery Separators',
  products: ['Hipore wet-process separator'],
  specialty: 'Premium safety performance',
  production_method: 'Wet process (proprietary)',
  capacity_million_sqm_year: 850,
  thickness_um: 10,
  porosity_percent: 40,
  tensile_strength_mpa: 140,
  shutdown_temperature_celsius: 130,
  thermal_stability: 'Industry leading',
  operating_since: 1997,
  workforce: 1100,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Panasonic', 'LG Energy Solution', 'Samsung SDI'],
  quality_rating: 'Premium',
  safety_record: 'Zero incidents in customer cells',
  premium_pricing: true,
  r_and_d_excellence: true,
  patents: 420,
  environmental_rating: 'A',
  expansion_plans: 'US facility for Tesla supply'
}),

// South Korea - SK ie technology
(mat_separator_sk:MaterialMfg {
  id: 'MAT-SEP-SK',
  name: 'SK ie technology',
  country: 'South Korea',
  region: 'Jeungpyeong, North Chungcheong',
  coordinates: [36.9167, 127.5833],
  material_type: 'Battery Separators',
  products: ['Wet-process PE separator', 'Ceramic-coated separator', 'High-voltage separator'],
  capacity_million_sqm_year: 1400,
  thickness_um: 9,
  porosity_percent: 43,
  ceramic_coating: 'Proprietary blend',
  operating_since: 2008,
  workforce: 1850,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['SK On', 'LG Energy Solution', 'Ford JV'],
  vertical_integration: 'SK Group battery ecosystem',
  expansion_plans: ['Poland', 'China', 'US'],
  environmental_rating: 'A-',
  renewable_energy_percent: 32
});

// ==================== SEMICONDUCTOR MATERIALS ====================
// Silicon wafers, photoresists, specialty gases

CREATE
// Taiwan - GlobalWafers
(mat_wafer_globalwafers:MaterialMfg {
  id: 'MAT-WAF-GLO',
  name: 'GlobalWafers Co. Ltd',
  country: 'Taiwan',
  region: 'Hsinchu',
  coordinates: [24.8047, 120.9714],
  material_type: 'Silicon Wafers',
  products: ['300mm silicon wafers', '200mm wafers', '150mm wafers'],
  wafer_300mm_capacity_million_wafers_year: 7.2,
  total_capacity_million_wafers_year: 12.5,
  operating_since: 1981,
  workforce: 8500,
  technology: 'Czochralski process',
  crystal_growing: 'Single crystal silicon ingots',
  wafer_thickness_um: 775,
  total_thickness_variation_um: '<0.5',
  nanotopography_nm: '<100',
  purity: '11N (99.999999999%)',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['TSMC', 'Samsung', 'Intel', 'UMC', 'GlobalFoundries'],
  market_position: 'World\'s 3rd largest',
  market_share_percent: 17,
  strategic_importance: 'Critical for semiconductor manufacturing',
  geopolitical_risk: 'Taiwan concentration',
  expansion_plans: 'US facility acquisition (SunEdison wafers)',
  environmental_rating: 'A-',
  renewable_energy_percent: 45
}),

// Japan - Shin-Etsu Chemical
(mat_wafer_shinetsu:MaterialMfg {
  id: 'MAT-WAF-SHI',
  name: 'Shin-Etsu Chemical Silicon Division',
  country: 'Japan',
  region: 'Gunma & Fukui',
  coordinates: [36.3911, 139.0608],
  material_type: 'Silicon Wafers & Polysilicon',
  products: ['300mm wafers', 'Polysilicon', 'Silicone materials'],
  wafer_capacity_million_wafers_year: 8.5,
  polysilicon_capacity_tonnes_year: 85000,
  operating_since: 1926,
  workforce: 12500,
  technology: 'Siemens process for polysilicon',
  vertical_integration: 'Polysilicon to finished wafer',
  purity: '11N',
  quality_rating: 'Industry benchmark',
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Intel', 'Samsung', 'TSMC', 'Micron'],
  market_position: 'World\'s largest wafer supplier',
  market_share_percent: 28,
  r_and_d_investment_usd_million_year: 320,
  environmental_rating: 'A',
  energy_efficiency: 'Best in class'
}),

// South Korea - SK Siltron
(mat_wafer_sksiltron:MaterialMfg {
  id: 'MAT-WAF-SKS',
  name: 'SK Siltron',
  country: 'South Korea',
  region: 'Gumi, North Gyeongsang',
  coordinates: [36.1192, 128.3444],
  material_type: 'Silicon Wafers',
  products: ['300mm wafers', '200mm wafers', 'SiC wafers'],
  wafer_300mm_capacity_million_wafers_year: 4.8,
  sic_wafer_capacity_thousand_wafers_year: 180,
  operating_since: 983,
  workforce: 3200,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Samsung', 'SK Hynix', 'TSMC'],
  acquisition: 'DuPont SiC wafer business (2019)',
  sic_expertise: 'Power electronics & EV applications',
  market_share_percent: 14,
  environmental_rating: 'A-'
}),

// USA - DuPont Electronics & Industrial
(mat_photoresist_dupont:MaterialMfg {
  id: 'MAT-PHOTO-DUP',
  name: 'DuPont Electronics & Industrial',
  country: 'USA',
  region: 'Rhode Island & Texas',
  coordinates: [41.8240, -71.4128],
  material_type: 'Photoresists & Specialty Chemicals',
  products: ['ArF photoresist', 'KrF photoresist', 'EUV photoresist', 'Developer solutions'],
  specialty: 'Advanced lithography materials',
  euv_photoresist_capability: true,
  process_node_nm: 5,
  next_gen_node_nm: 3,
  operating_since: 1802,
  electronics_division_since: 1958,
  workforce: 4500,
  technology: 'Chemically amplified resists',
  resolution_nm: 13,
  sensitivity_mj_cm2: 25,
  line_edge_roughness_nm: '<2',
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Intel', 'TSMC', 'Samsung', 'GlobalFoundries'],
  strategic_importance: 'Critical for sub-7nm manufacturing',
  r_and_d_investment_usd_million_year: 450,
  patents: 8500,
  export_controls: 'Subject to US regulations',
  environmental_rating: 'A',
  sustainability_leader: true
}),

// Japan - JSR Corporation
(mat_photoresist_jsr:MaterialMfg {
  id: 'MAT-PHOTO-JSR',
  name: 'JSR Corporation',
  country: 'Japan',
  region: 'Yokkaichi, Mie',
  coordinates: [34.9667, 136.6250],
  material_type: 'Photoresists',
  products: ['EUV photoresist', 'ArF photoresist', 'Multi-patterning materials'],
  specialty: 'Leading EUV resist supplier',
  euv_market_share_percent: 35,
  operating_since: 1957,
  workforce: 3800,
  technology: 'Advanced polymer chemistry',
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['TSMC', 'Samsung', 'Intel', 'SK Hynix'],
  strategic_acquisition: 'Announced acquisition by JSR for $6.4B (2023)',
  r_and_d_excellence: true,
  patents: 2400,
  environmental_rating: 'A'
});

// Success message
MATCH (n:MaterialMfg)
RETURN 'Part 4 Complete: Created ' + count(n) + ' advanced material manufacturer nodes' as message;
