// ==================== PART 5: COMPONENT MANUFACTURERS ====================
// These companies produce finished components: battery cells, displays,
// processors, cameras, memory, etc.

// Create indexes
CREATE INDEX component_id IF NOT EXISTS FOR (c:ComponentMfg) ON (c.id);

// ==================== BATTERY CELL MANUFACTURERS ====================

CREATE
// China - CATL (Contemporary Amperex Technology Co. Limited)
(comp_battery_catl:ComponentMfg {
  id: 'COMP-BAT-CATL',
  name: 'CATL (Contemporary Amperex Technology Co. Limited)',
  country: 'China',
  region: 'Ningde, Fujian',
  coordinates: [26.6617, 119.5478],
  component_type: 'Lithium-ion Battery Cells',
  products: ['NMC cylindrical cells', 'NMC pouch cells', 'LFP prismatic cells', 'CTP battery packs'],
  cell_formats: ['Cylindrical 21700', 'Cylindrical 4680', 'Pouch', 'Prismatic'],
  chemistry_types: ['NMC 811', 'LFP', 'LMFP', 'Sodium-ion'],
  annual_capacity_gwh: 450,
  capacity_expansion_2025_gwh: 670,
  operating_since: 2011,
  workforce: 75000,
  facilities_count: 14,
  facility_locations: ['China (10)', 'Germany (1)', 'Hungary (1)', 'USA (planned)'],
  energy_density_wh_kg: 285,
  cycle_life: 3000,
  fast_charge_capability: '10-80% in 10 minutes',
  warranty_years: 8,
  warranty_km: 800000,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001', 'UL', 'VDA'],
  customer_base: ['Tesla', 'BMW', 'VW', 'Mercedes', 'Ford', 'Toyota', 'Honda', 'Nio', 'Xpeng'],
  market_position: 'World\'s largest battery manufacturer',
  market_share_percent: 37,
  revenue_usd_billion_2023: 50,
  r_and_d_investment_usd_billion_year: 3.2,
  patents: 15700,
  innovation: ['CTP 3.0 (Cell-to-Pack)', 'Qilin battery', 'Sodium-ion batteries'],
  next_gen_tech: ['Solid-state batteries', 'Silicon anode', '500Wh/kg target'],
  environmental_rating: 'B+',
  carbon_neutral_target_year: 2035,
  recycling_capacity_gwh_year: 25,
  battery_passport: true,
  strategic_importance: 'Dominates global EV battery market'
}),

// South Korea - LG Energy Solution
(comp_battery_lges:ComponentMfg {
  id: 'COMP-BAT-LGES',
  name: 'LG Energy Solution',
  parent_company: 'LG Chem (spun off 2020)',
  country: 'South Korea',
  region: 'Seoul & Ochang',
  coordinates: [37.5665, 126.9780],
  component_type: 'Lithium-ion Battery Cells',
  products: ['NMC pouch cells', 'NCMA cells', 'Cylindrical 21700', 'Cylindrical 4680'],
  chemistry_types: ['NCMA (89% Ni)', 'NMC 712', 'NCA'],
  annual_capacity_gwh: 260,
  capacity_expansion_2025_gwh: 430,
  operating_since: 1992,
  workforce: 42000,
  facilities_count: 11,
  facility_locations: ['South Korea (4)', 'China (3)', 'Poland (1)', 'USA (3)'],
  energy_density_wh_kg: 290,
  cycle_life: 3500,
  fast_charge_capability: '10-80% in 12 minutes',
  warranty_years: 10,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001', 'UL', 'VDA'],
  customer_base: ['Tesla (4680)', 'GM Ultium', 'Ford', 'Hyundai', 'Kia', 'Volvo', 'Rivian'],
  market_position: 'World\'s 2nd largest',
  market_share_percent: 14,
  revenue_usd_billion_2023: 22,
  r_and_d_investment_usd_billion_year: 1.8,
  patents: 28000,
  innovation: ['NCMA cathode (low cobalt)', 'Safety reinforced separator', '4680 production'],
  quality_rating: 'Premium',
  recall_history: 'GM Bolt recall (2021)',
  quality_improvements_post_recall: 'Enhanced QC + x-ray inspection',
  environmental_rating: 'A-',
  carbon_neutral_target_year: 2030,
  renewable_energy_percent: 42,
  battery_passport: true
}),

// South Korea - Samsung SDI
(comp_battery_sdi:ComponentMfg {
  id: 'COMP-BAT-SDI',
  name: 'Samsung SDI',
  parent_company: 'Samsung Group',
  country: 'South Korea',
  region: 'Yongin, Gyeonggi',
  coordinates: [37.2636, 127.2400],
  component_type: 'Lithium-ion Battery Cells',
  products: ['NCA prismatic cells', 'NMC pouch cells', 'Gen 5 prismatic cells', 'Solid-state (development)'],
  chemistry_types: ['NCA', 'NMC 811', 'NMC 9½½'],
  annual_capacity_gwh: 145,
  capacity_expansion_2025_gwh: 250,
  operating_since: 1970,
  battery_division_since: 1999,
  workforce: 28000,
  facilities_count: 8,
  facility_locations: ['South Korea (3)', 'China (1)', 'Hungary (2)', 'USA (2)'],
  energy_density_wh_kg: 300,
  gen5_energy_density_wh_kg: 310,
  cycle_life: 4000,
  fast_charge_capability: '10-80% in 9 minutes',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001', 'UL'],
  customer_base: ['BMW', 'VW', 'Stellantis', 'Ford', 'Rivian', 'Genesis', 'Lucid'],
  market_position: 'World\'s 4th largest',
  market_share_percent: 9,
  revenue_usd_billion_2023: 14,
  r_and_d_investment_usd_billion_year: 1.2,
  patents: 12500,
  innovation: ['Gen 5 prismatic cells', 'All-solid-state battery', 'Silicon anode'],
  solid_state_timeline: 'Pilot production 2027',
  quality_rating: 'Premium',
  environmental_rating: 'A',
  renewable_energy_percent: 38,
  strategic_focus: 'Premium automotive segment'
}),

// Japan - Panasonic Energy
(comp_battery_panasonic:ComponentMfg {
  id: 'COMP-BAT-PAN',
  name: 'Panasonic Energy Co. Ltd',
  parent_company: 'Panasonic Holdings',
  country: 'Japan',
  region: 'Osaka',
  coordinates: [34.6937, 135.5023],
  component_type: 'Lithium-ion Battery Cells',
  products: ['Cylindrical 18650', 'Cylindrical 21700', 'Cylindrical 4680'],
  chemistry_types: ['NCA (Sumitomo cathode)', 'High-nickel NCA'],
  annual_capacity_gwh: 95,
  capacity_expansion_gwh: 'Kansas 4680 plant',
  operating_since: 1923,
  battery_partnership_tesla_since: 2009,
  workforce: 18000,
  facilities_count: 6,
  facility_locations: ['Japan (2)', 'China (1)', 'USA Nevada (1)', 'USA Kansas (1 under construction)'],
  energy_density_wh_kg: 260,
  energy_density_4680_wh_kg: 272,
  cycle_life: 5000,
  calendar_life_years: 20,
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001', 'UL'],
  customer_base: ['Tesla (primary)', 'Subaru', 'Mazda'],
  tesla_exclusive: 'Historically, diversifying now',
  market_position: 'Specialized in cylindrical cells',
  market_share_percent: 6,
  revenue_usd_billion_2023: 8,
  r_and_d_partnership: 'Joint development with Tesla',
  innovation: ['4680 production scaling', 'Dry electrode coating (with Tesla)'],
  quality_rating: 'Industry leading',
  quality_consistency: 'Extremely high',
  defect_rate_ppm: '<5',
  environmental_rating: 'A',
  renewable_energy_nevada: 'Solar + grid',
  strategic_importance: 'Tesla\'s primary battery partner'
}),

// China - BYD Battery Division
(comp_battery_byd:ComponentMfg {
  id: 'COMP-BAT-BYD',
  name: 'BYD FinDreams Battery (Shenzhen FinDreams Battery Co. Ltd)',
  parent_company: 'BYD Company',
  country: 'China',
  region: 'Shenzhen, Guangdong',
  coordinates: [22.5431, 114.0579],
  component_type: 'Lithium-ion Battery Cells',
  products: ['LFP Blade Battery', 'LFP prismatic cells', 'NMC cells'],
  chemistry_types: ['LFP (primary)', 'NMC'],
  specialty: 'LFP Blade Battery innovation',
  annual_capacity_gwh: 285,
  capacity_expansion_2025_gwh: 400,
  operating_since: 1995,
  blade_battery_launch: 2020,
  workforce: 52000,
  facilities_count: 12,
  facility_locations: ['China (10)', 'Brazil (1)', 'Thailand (1)'],
  blade_battery_energy_density_wh_kg: 150,
  blade_battery_volumetric_wh_l: 332,
  cycle_life: 4500,
  safety_rating: 'Passed nail penetration test',
  thermal_runaway_resistance: 'Excellent',
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['BYD vehicles (primary)', 'Tesla (Model Y)', 'Toyota', 'Ford (Europe)'],
  vertical_integration: 'BYD makes own batteries for own cars',
  external_sales_started: 2022,
  market_position: 'World\'s 3rd largest',
  market_share_percent: 16,
  revenue_usd_billion_2023: 28,
  innovation: ['Blade Battery', 'Cell-to-body integration', 'LFP cost leadership'],
  cost_advantage: 'Lowest $/kWh for LFP',
  environmental_rating: 'B+',
  cobalt_free: true,
  strategic_advantage: 'Vertical integration + LFP expertise'
});

// ==================== DISPLAY MANUFACTURERS ====================

CREATE
// South Korea - Samsung Display
(comp_display_samsung:ComponentMfg {
  id: 'COMP-DISP-SAM',
  name: 'Samsung Display',
  parent_company: 'Samsung Electronics',
  country: 'South Korea',
  region: 'Asan, South Chungcheong',
  coordinates: [36.7836, 127.0045],
  component_type: 'AMOLED Displays',
  products: ['Flexible AMOLED', 'Rigid AMOLED', 'LTPO AMOLED', 'Foldable displays'],
  display_sizes: ['5.8" to 7.6"', 'Foldable 7.6" to 8.0"'],
  technology: 'LTPO (Low-Temperature Polycrystalline Oxide)',
  resolution_ppi: 500,
  refresh_rate_hz: 120,
  ltpo_variable_refresh: '1-120Hz adaptive',
  brightness_nits: 1750,
  contrast_ratio: 'Infinite (OLED)',
  color_gamut_percent_dci_p3: 100,
  annual_capacity_million_units: 550,
  operating_since: 1991,
  oled_production_since: 2007,
  workforce: 42000,
  facilities_count: 7,
  facility_locations: ['South Korea (5)', 'Vietnam (2)'],
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple (iPhone)', 'Samsung (Galaxy)', 'Google (Pixel)', 'Xiaomi', 'Oppo'],
  market_position: 'World\'s largest OLED display maker',
  market_share_percent: 52,
  revenue_usd_billion_2023: 28,
  r_and_d_investment_usd_billion_year: 2.8,
  patents: 8900,
  innovation: ['Eco² OLED (reduced power)', 'UPC (Under Panel Camera)', 'Foldable display technology'],
  foldable_expertise: 'Exclusive supplier for Galaxy Z series',
  quality_rating: 'Premium',
  defect_rate_ppm: 8,
  environmental_rating: 'A-',
  hazardous_substance_free: 'RoHS compliant'
}),

// South Korea - LG Display
(comp_display_lg:ComponentMfg {
  id: 'COMP-DISP-LG',
  name: 'LG Display',
  country: 'South Korea',
  region: 'Paju, Gyeonggi',
  coordinates: [37.7608, 126.7797],
  component_type: 'OLED & LCD Displays',
  products: ['P-OLED (plastic OLED)', 'LTPS LCD', 'OLED TV panels'],
  display_sizes_mobile: ['6.1" to 6.8"'],
  technology: 'P-OLED (Plastic substrate)',
  resolution_ppi: 460,
  refresh_rate_hz: 120,
  brightness_nits: 1200,
  annual_capacity_million_units: 180,
  operating_since: 1985,
  oled_mobile_since: 2016,
  workforce: 62000,
  facilities_count: 12,
  facility_locations: ['South Korea (7)', 'China (4)', 'Vietnam (1)'],
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple (iPhone, Watch)', 'Xiaomi', 'Google', 'Motorola', 'OnePlus'],
  market_position: 'World\'s 2nd largest mobile OLED',
  market_share_percent: 22,
  revenue_usd_billion_2023: 18,
  r_and_d_investment_usd_billion_year: 1.4,
  strategic_challenges: 'Lagging Samsung in mobile OLED',
  tv_oled_dominance: 'Leading TV OLED supplier',
  environmental_rating: 'A-'
}),

// China - BOE Technology Group
(comp_display_boe:ComponentMfg {
  id: 'COMP-DISP-BOE',
  name: 'BOE Technology Group',
  country: 'China',
  region: 'Beijing',
  coordinates: [39.9042, 116.4074],
  component_type: 'AMOLED & LCD Displays',
  products: ['Flexible AMOLED', 'Rigid AMOLED', 'LTPS LCD', 'a-Si LCD'],
  display_sizes: ['5.5" to 7.5"'],
  technology: 'Flexible AMOLED',
  resolution_ppi: 450,
  refresh_rate_hz: 120,
  brightness_nits: 1400,
  annual_capacity_million_units_oled: 280,
  annual_capacity_million_units_lcd: 820,
  operating_since: 1993,
  oled_production_since: 2017,
  workforce: 85000,
  facilities_count: 16,
  facility_locations: ['China (14)', 'Vietnam (1)', 'India (1)'],
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple (iPad, MacBook)', 'Huawei', 'Xiaomi', 'Oppo', 'Vivo', 'Honor'],
  apple_iphone_certification: 'Achieved 2023',
  market_position: 'World\'s largest LCD, growing OLED',
  market_share_oled_percent: 11,
  market_share_lcd_percent: 24,
  revenue_usd_billion_2023: 20,
  r_and_d_investment_usd_billion_year: 1.6,
  patents: 95000,
  innovation: ['Under-display camera', 'Rollable displays', '8K displays'],
  strategic_goal: 'Challenge Samsung in OLED',
  quality_improvements: 'Significant progress 2020-2023',
  environmental_rating: 'B+',
  government_support: 'Strategic Chinese industry'
});

// ==================== SEMICONDUCTOR PROCESSORS ====================

CREATE
// Taiwan - TSMC (Taiwan Semiconductor Manufacturing Company)
(comp_chip_tsmc:ComponentMfg {
  id: 'COMP-CHIP-TSMC',
  name: 'Taiwan Semiconductor Manufacturing Company (TSMC)',
  country: 'Taiwan',
  region: 'Hsinchu Science Park',
  coordinates: [24.7807, 120.9972],
  component_type: 'Semiconductor Foundry (Contract Chip Manufacturing)',
  products: ['Application Processors (AP)', 'Modems', 'AI/ML chips', 'GPU', 'CPU', 'Custom ASICs'],
  process_nodes: ['3nm (N3)', '5nm (N5)', '7nm (N7)', '16nm', '28nm'],
  leading_edge_node: '3nm',
  next_gen_node: '2nm (N2) - 2025',
  wafer_capacity_million_wafers_year_12inch: 15.5,
  operating_since: 1987,
  workforce: 73000,
  facilities_count: 14,
  fab_locations: ['Taiwan (12)', 'China Nanjing (1)', 'USA Arizona (1 under construction)'],
  technology_leadership: 'Industry leading process technology',
  euv_lithography: true,
  euv_machines_count: 100,
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001', 'ISO 50001'],
  customer_base: ['Apple (A-series, M-series)', 'AMD', 'NVIDIA', 'Qualcomm', 'MediaTek', 'Intel'],
  apple_revenue_percent: 25,
  market_position: 'World\'s largest contract chip maker',
  market_share_foundry_percent: 59,
  revenue_usd_billion_2023: 70,
  profit_margin_percent: 42,
  r_and_d_investment_usd_billion_year: 8.5,
  capex_usd_billion_year: 36,
  innovation: ['3nm GAA (Gate-All-Around)', '2nm development', 'Advanced packaging'],
  advanced_packaging: ['CoWoS', 'InFO', 'SoIC'],
  strategic_importance: 'Irreplaceable in global chip supply',
  geopolitical_risk: 'Taiwan concentration',
  us_fab_investment_usd_billion: 40,
  environmental_rating: 'A',
  renewable_energy_percent: 12,
  renewable_energy_target_2030_percent: 40,
  water_recycling_percent: 86
}),

// South Korea - Samsung Foundry
(comp_chip_samsung:ComponentMfg {
  id: 'COMP-CHIP-SAM',
  name: 'Samsung Foundry',
  parent_company: 'Samsung Electronics',
  country: 'South Korea',
  region: 'Hwaseong, Gyeonggi',
  coordinates: [37.2050, 127.0614],
  component_type: 'Semiconductor Foundry & Memory',
  products: ['Exynos Application Processors', 'Image sensors', 'DRAM', 'NAND flash', 'Custom chips'],
  process_nodes: ['3nm GAA', '4nm', '5nm', '7nm', '8nm'],
  leading_edge_node: '3nm GAA',
  gaa_technology: 'Gate-All-Around (MBCFET)',
  wafer_capacity_million_wafers_year_12inch: 3.8,
  operating_since: 1969,
  foundry_business_since: 2017,
  workforce: 118000,
  facilities_count: 6,
  fab_locations: ['South Korea (5)', 'USA Texas (1 planned)'],
  euv_lithography: true,
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Samsung (internal)', 'Qualcomm', 'NVIDIA', 'AMD', 'IBM'],
  market_position: 'World\'s 2nd largest foundry',
  market_share_foundry_percent: 13,
  revenue_foundry_usd_billion_2023: 14,
  revenue_total_usd_billion_2023: 210,
  r_and_d_investment_usd_billion_year: 24,
  capex_usd_billion_year: 28,
  innovation: ['3nm GAA transistors', 'Backside power delivery', 'Hybrid bonding'],
  strategic_challenge: 'Closing gap with TSMC',
  yield_challenges: 'Lower than TSMC at leading edge',
  environmental_rating: 'A-',
  renewable_energy_percent: 18
}),

// USA - Intel Foundry Services
(comp_chip_intel:ComponentMfg {
  id: 'COMP-CHIP-INT',
  name: 'Intel Foundry Services (IFS)',
  parent_company: 'Intel Corporation',
  country: 'USA',
  region: 'Oregon, Arizona, New Mexico',
  coordinates: [45.5408, -122.8571],
  component_type: 'Semiconductor Manufacturing',
  products: ['x86 processors', 'Server CPUs', 'Mobile processors', 'Foundry services'],
  process_nodes: ['Intel 4 (7nm)', 'Intel 3 (5nm)', 'Intel 20A (2nm-class)', 'Intel 18A (1.8nm-class)'],
  leading_edge_node: 'Intel 4',
  next_gen_nodes: ['Intel 3 (2024)', 'Intel 20A (2024)', 'Intel 18A (2025)'],
  wafer_capacity_million_wafers_year_12inch: 8.2,
  operating_since: 1968,
  foundry_services_launch: 2021,
  workforce: 124000,
  facilities_count: 11,
  fab_locations: ['USA Oregon (3)', 'USA Arizona (2)', 'USA New Mexico (1)', 'Ireland (1)', 'Israel (2)', 'Germany (1 under construction)', 'Poland (1 planned)'],
  euv_lithography: true,
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base_foundry: ['US government', 'MediaTek', 'Amazon', 'Microsoft (potential)'],
  market_position: 'Historically dominant x86, emerging foundry',
  revenue_usd_billion_2023: 54,
  revenue_client_computing_usd_billion: 30,
  revenue_datacenter_usd_billion: 15,
  r_and_d_investment_usd_billion_year: 17,
  capex_usd_billion_year: 25,
  innovation: ['RibbonFET (GAA)', 'PowerVia (backside power)', 'Foveros 3D packaging'],
  strategic_turnaround: 'IDM 2.0 strategy',
  us_chips_act_funding_usd_billion: 8.5,
  geopolitical_importance: 'US semiconductor independence',
  environmental_rating: 'A',
  renewable_energy_percent: 93,
  carbon_neutral_operations: 2040,
  water_restoration: '100% by 2030'
});

// ==================== CAMERA MODULE MANUFACTURERS ====================

CREATE
// South Korea - LG Innotek
(comp_camera_lginnotek:ComponentMfg {
  id: 'COMP-CAM-LGI',
  name: 'LG Innotek Camera Module Division',
  parent_company: 'LG Corporation',
  country: 'South Korea',
  region: 'Pyeongtaek, Gyeonggi',
  coordinates: [36.9921, 127.1128],
  component_type: 'Camera Modules',
  products: ['Multi-camera modules', 'Periscope telephoto', 'Wide-angle', 'Ultra-wide', 'ToF sensors'],
  camera_types: ['Main (wide)', 'Ultra-wide', 'Telephoto (periscope)', '3D ToF'],
  resolution_mp: [108, 64, 48, 12],
  sensor_size: '1/1.33" (main)',
  pixel_size_um: 0.8,
  aperture_main: 'f/1.5',
  optical_zoom: '5x periscope',
  image_stabilization: 'OIS + EIS',
  autofocus: 'Dual Pixel PDAF',
  annual_capacity_million_modules: 480,
  operating_since: 1970,
  camera_business_since: 2004,
  workforce: 18000,
  facilities_count: 5,
  facility_locations: ['South Korea (3)', 'Vietnam (1)', 'China (1)'],
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple (primary)', 'Samsung', 'Google', 'Xiaomi'],
  apple_exclusive: 'Main camera module supplier',
  market_position: 'Premium segment leader',
  market_share_percent: 28,
  revenue_usd_billion_2023: 9,
  r_and_d_investment_usd_million_year: 450,
  innovation: ['Folded zoom optics', 'Advanced OIS', 'Thin camera modules'],
  quality_rating: 'Premium',
  defect_rate_ppm: 12,
  environmental_rating: 'A-'
}),

// Japan - Sony Semiconductor Solutions
(comp_camera_sony:ComponentMfg {
  id: 'COMP-CAM-SONY',
  name: 'Sony Semiconductor Solutions',
  parent_company: 'Sony Group',
  country: 'Japan',
  region: 'Kumamoto',
  coordinates: [32.8032, 130.7079],
  component_type: 'Image Sensors & Camera Modules',
  products: ['CMOS image sensors', 'Camera modules', 'ToF sensors'],
  sensor_technology: 'Stacked CMOS',
  sensor_types: ['IMX sensor series', 'Exmor RS'],
  resolution_mp: [200, 108, 64, 50, 48],
  sensor_size_main: '1" (Type 1.0)',
  pixel_size_um: 1.2,
  readout_speed_fps: 960,
  hdr_capability: 'Real-time HDR',
  low_light_performance: 'Industry leading',
  annual_capacity_million_sensors: 920,
  operating_since: 1946,
  image_sensor_since: 2000,
  workforce: 22000,
  facilities_count: 4,
  facility_locations: ['Japan (3)', 'Taiwan (1)'],
  certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple', 'Samsung', 'Xiaomi', 'Oppo', 'Vivo', 'Google', 'Sony Mobile'],
  market_position: 'World\'s largest image sensor supplier',
  market_share_percent: 44,
  revenue_usd_billion_2023: 12,
  r_and_d_investment_usd_billion_year: 1.1,
  patents: 15000,
  innovation: ['2-layer transistor pixel', 'AI processing on sensor', 'Global shutter CMOS'],
  strategic_advantage: 'Technology leadership',
  supply_constraints: 'High demand exceeds capacity',
  expansion_investment_usd_billion: 2.1,
  environmental_rating: 'A'
}),

// China - Sunny Optical
(comp_camera_sunny:ComponentMfg {
  id: 'COMP-CAM-SUN',
  name: 'Sunny Optical Technology',
  country: 'China',
  region: 'Yuyao, Zhejiang',
  coordinates: [30.0457, 121.1544],
  component_type: 'Camera Modules & Optical Components',
  products: ['Camera modules', 'Lens assemblies', 'Actuators'],
  annual_capacity_million_modules: 1200,
  operating_since: 1984,
  smartphone_cameras_since: 2004,
  workforce: 48000,
  facilities_count: 12,
  facility_locations: ['China (10)', 'South Korea (1)', 'Vietnam (1)'],
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001'],
  customer_base: ['Samsung', 'Huawei', 'Xiaomi', 'Oppo', 'Vivo', 'Honor'],
  market_position: 'Largest by volume',
  market_share_percent: 18,
  revenue_usd_billion_2023: 5.8,
  segment: 'Mid-range to flagship',
  cost_competitiveness: 'High',
  environmental_rating: 'B+'
});

// ==================== MEMORY MANUFACTURERS ====================

CREATE
// South Korea - Samsung Memory
(comp_memory_samsung:ComponentMfg {
  id: 'COMP-MEM-SAM',
  name: 'Samsung Memory Division',
  parent_company: 'Samsung Electronics',
  country: 'South Korea',
  region: 'Pyeongtaek, Gyeonggi',
  coordinates: [36.9921, 127.1128],
  component_type: 'Memory (DRAM & NAND Flash)',
  products: ['LPDDR5X DRAM', 'UFS 4.0 NAND', 'eMMC', 'V-NAND'],
  dram_types: ['LPDDR5X', 'LPDDR5', 'DDR5', 'DDR4'],
  lpddr5x_speed_gbps: 8.5,
  lpddr5x_capacity_gb: 16,
  nand_types: ['V-NAND 8th gen (236-layer)', 'UFS 4.0', 'eMMC 5.1'],
  nand_layer_count: 236,
  ufs_4_0_speed_gbps: 4.2,
  nand_capacity_tb: 2,
  annual_capacity_million_wafers_year: 4.2,
  operating_since: 1974,
  memory_leadership_since: 1992,
  workforce: 48000,
  facilities_count: 5,
  fab_locations: ['South Korea Pyeongtaek (2)', 'South Korea Hwaseong (1)', 'China Xi\'an (2)'],
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple', 'Samsung (internal)', 'Xiaomi', 'Oppo', 'Vivo', 'Server/PC OEMs'],
  market_position_dram: 'World\'s largest',
  market_share_dram_percent: 42,
  market_position_nand: 'World\'s largest',
  market_share_nand_percent: 32,
  revenue_usd_billion_2023: 58,
  r_and_d_investment_usd_billion_year: 8.2,
  capex_usd_billion_year: 18,
  innovation: ['8th gen V-NAND', 'GAA DRAM (development)', 'CXL memory'],
  technology_leadership: 'Industry leading',
  environmental_rating: 'A-',
  renewable_energy_percent: 22
}),

// South Korea - SK Hynix
(comp_memory_hynix:ComponentMfg {
  id: 'COMP-MEM-HYN',
  name: 'SK Hynix',
  parent_company: 'SK Group',
  country: 'South Korea',
  region: 'Icheon, Gyeonggi',
  coordinates: [37.2793, 127.4419],
  component_type: 'Memory (DRAM & NAND Flash)',
  products: ['LPDDR5X DRAM', 'UFS 3.1', 'HBM3 (High Bandwidth Memory)', 'V-NAND'],
  dram_types: ['LPDDR5X', 'LPDDR5', 'DDR5', 'HBM3'],
  hbm3_leadership: 'Leading supplier for AI/ML chips',
  nand_types: ['4D NAND (238-layer)', 'UFS 3.1'],
  nand_layer_count: 238,
  annual_capacity_million_wafers_year: 2.8,
  operating_since: 1983,
  workforce: 32000,
  facilities_count: 6,
  fab_locations: ['South Korea Icheon (2)', 'South Korea Cheongju (1)', 'China Wuxi (2)', 'USA (Intel NAND acquired)'],
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple', 'AMD', 'NVIDIA', 'Intel', 'Server OEMs'],
  market_position_dram: 'World\'s 2nd largest',
  market_share_dram_percent: 28,
  market_position_nand: 'World\'s 4th largest',
  market_share_nand_percent: 12,
  revenue_usd_billion_2023: 28,
  strategic_focus: 'HBM for AI accelerators',
  hbm_customers: ['NVIDIA H100/H200', 'AMD MI300'],
  intel_nand_acquisition: 'Acquired Intel\'s NAND business (2021)',
  environmental_rating: 'A-'
}),

// USA - Micron Technology
(comp_memory_micron:ComponentMfg {
  id: 'COMP-MEM-MIC',
  name: 'Micron Technology',
  country: 'USA',
  region: 'Boise, Idaho',
  coordinates: [43.6150, -116.2023],
  component_type: 'Memory (DRAM & NAND Flash)',
  products: ['LPDDR5X', 'UFS 4.0', 'HBM3E', '232-layer NAND'],
  dram_types: ['LPDDR5X', 'LPDDR5', 'DDR5', 'HBM3E'],
  hbm3e_capability: 'Next-gen high bandwidth memory',
  nand_types: ['232-layer 3D NAND', 'UFS 4.0'],
  nand_layer_count: 232,
  annual_capacity_million_wafers_year: 1.9,
  operating_since: 1978,
  workforce: 48000,
  facilities_count: 9,
  fab_locations: ['USA Idaho (1)', 'USA Virginia (1)', 'USA New York (expansion)', 'Japan Hiroshima (1)', 'Taiwan Taichung (2)', 'Singapore (2)'],
  certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 45001'],
  customer_base: ['Apple', 'Server OEMs', 'Automotive', 'Industrial'],
  market_position_dram: 'World\'s 3rd largest',
  market_share_dram_percent: 23,
  market_position_nand: 'World\'s 5th largest',
  market_share_nand_percent: 11,
  revenue_usd_billion_2023: 15,
  r_and_d_investment_usd_billion_year: 3.2,
  us_chips_act_funding_usd_billion: 6.1,
  strategic_importance: 'Only US-headquartered major memory maker',
  geopolitical_advantage: 'US government support',
  environmental_rating: 'A',
  renewable_energy_percent: 38,
  carbon_neutrality_target: 2050
});

// Success message
MATCH (n:ComponentMfg)
RETURN 'Part 5 Complete: Created ' + count(n) + ' component manufacturer nodes' as message;
