// ==================== PART 2: PROCESSORS & REFINERIES ====================
// This creates the processing layer that takes raw materials from mines
// and refines them into usable industrial materials

// Create indexes for performance
CREATE INDEX processor_id IF NOT EXISTS FOR (p:Processor) ON (p.id);
CREATE INDEX refinery_id IF NOT EXISTS FOR (r:Refinery) ON (r.id);
CREATE INDEX smelter_id IF NOT EXISTS FOR (s:Smelter) ON (s.id);

// ==================== COPPER SMELTERS & REFINERIES ====================
// Convert copper ore into refined copper cathodes (99.99% pure)

CREATE
// Chile - Ventanas Smelter (processes Escondida & Chuquicamata ore)
(smelter_cu_ventanas:Smelter {
  id: 'SMELT-CU-VEN',
  name: 'Ventanas Smelter',
  country: 'Chile',
  region: 'Valparaíso',
  coordinates: [-32.7339, -71.4936],
  owner: 'Codelco',
  ownership_percent: 100,
  operating_since: 1964,
  process_type: 'Flash Smelting',
  technology: 'Outotec Flash Furnace',
  annual_capacity_tonnes: 340000,
  annual_production_tonnes: 320000,
  input_material: 'Copper Concentrate',
  output_material: 'Blister Copper 98.5%',
  output_purity_percent: 98.5,
  workforce: 850,
  power_consumption_mw: 45,
  furnace_temperature_celsius: 1250,
  environmental_rating: 'C+',
  so2_capture_percent: 95,
  acid_plant: true,
  sulfuric_acid_production_kt_year: 850,
  certifications: ['ISO 14001', 'ISO 9001'],
  modernization_investment_usd_million: 180,
  closure_planned: 2025,
  closure_reason: 'Environmental regulations',
  replacement_facility: 'New smelter in northern Chile'
}),

(refinery_cu_ventanas:Refinery {
  id: 'REF-CU-VEN',
  name: 'Ventanas Refinery',
  country: 'Chile',
  region: 'Valparaíso',
  coordinates: [-32.7339, -71.4936],
  owner: 'Codelco',
  ownership_percent: 100,
  operating_since: 1966,
  process_type: 'Electrorefining',
  annual_capacity_tonnes: 335000,
  annual_production_tonnes: 315000,
  input_material: 'Blister Copper',
  output_material: 'Copper Cathode',
  output_purity_percent: 99.99,
  cathode_type: 'Grade A Cathode',
  lme_registered: true,
  workforce: 420,
  power_consumption_mw: 28,
  certifications: ['ISO 14001', 'ISO 9001', 'LME Approved'],
  quality_standards: ['ASTM B115', 'EN 1978'],
  precious_metals_recovery: true,
  gold_recovery_kg_year: 1200,
  silver_recovery_kg_year: 45000
}),

// Japan - Onahama Smelter (processes imported concentrate)
(smelter_cu_onahama:Smelter {
  id: 'SMELT-CU-ONA',
  name: 'Onahama Smelter',
  country: 'Japan',
  region: 'Fukushima',
  coordinates: [36.9431, 140.9022],
  owner: 'LS-Nikko Copper',
  ownership_percent: 100,
  operating_since: 1970,
  process_type: 'Mitsubishi Continuous Process',
  technology: 'S-bath, C-bath, A-bath',
  annual_capacity_tonnes: 360000,
  annual_production_tonnes: 350000,
  input_material: 'Copper Concentrate',
  output_material: 'Copper Cathode 99.99%',
  output_purity_percent: 99.99,
  workforce: 680,
  environmental_rating: 'A-',
  so2_capture_percent: 99.5,
  zero_discharge_system: true,
  certifications: ['ISO 14001', 'ISO 45001', 'ISO 50001', 'LME Approved'],
  energy_efficiency_rating: 'Best in class',
  waste_heat_recovery: true,
  precious_metals_facility: true,
  gold_recovery_kg_year: 2500,
  silver_recovery_kg_year: 85000,
  selenium_recovery_tonnes_year: 45,
  tellurium_recovery_tonnes_year: 12
}),

// South Korea - Onsan Smelter
(smelter_cu_onsan:Smelter {
  id: 'SMELT-CU-ONS',
  name: 'Onsan Copper Smelter',
  country: 'South Korea',
  region: 'Ulsan',
  coordinates: [35.4333, 129.3500],
  owner: 'LS-Nikko Copper',
  ownership_percent: 100,
  operating_since: 1978,
  process_type: 'Mitsubishi Continuous Process',
  annual_capacity_tonnes: 450000,
  annual_production_tonnes: 430000,
  input_material: 'Copper Concentrate',
  output_material: 'Copper Cathode',
  output_purity_percent: 99.99,
  workforce: 920,
  environmental_rating: 'A',
  certifications: ['ISO 14001', 'ISO 45001', 'ISO 9001', 'LME Approved'],
  so2_capture_percent: 99.8,
  sulfuric_acid_production_kt_year: 1200,
  co2_emissions_kt_year: 180,
  renewable_energy_percent: 8,
  automation_level: 'High',
  quality_control_labs: 3
}),

// China - Guixi Smelter (world's largest)
(smelter_cu_guixi:Smelter {
  id: 'SMELT-CU-GUI',
  name: 'Guixi Copper Smelter',
  country: 'China',
  region: 'Jiangxi Province',
  coordinates: [28.2925, 117.2089],
  owner: 'Jiangxi Copper Corporation',
  ownership_type: 'State-owned enterprise',
  operating_since: 1979,
  process_type: 'Flash Smelting + Bottom Blowing',
  annual_capacity_tonnes: 1000000,
  annual_production_tonnes: 950000,
  capacity_note: 'World\'s largest single-site copper smelter',
  input_material: 'Copper Concentrate',
  output_material: 'Copper Cathode',
  output_purity_percent: 99.99,
  workforce: 3500,
  environmental_rating: 'B',
  certifications: ['ISO 14001', 'ISO 9001'],
  expansion_history: ['1979: 100kt', '2000: 400kt', '2010: 800kt', '2020: 1000kt'],
  sulfuric_acid_production_kt_year: 2800,
  precious_metals_recovery: true,
  gold_recovery_kg_year: 8000,
  silver_recovery_kg_year: 280000,
  strategic_importance: 'National security resource'
}),

// Indonesia - Gresik Smelter (processes Grasberg concentrate)
(smelter_cu_gresik:Smelter {
  id: 'SMELT-CU-GRE',
  name: 'PT Smelting Gresik',
  country: 'Indonesia',
  region: 'East Java',
  coordinates: [-7.1615, 112.6533],
  owner: 'Mitsubishi Materials',
  ownership_percent: 60.5,
  partner_1: 'Freeport Indonesia',
  partner_1_percent: 25,
  government_ownership_percent: 14.5,
  operating_since: 1998,
  process_type: 'Mitsubishi Continuous Process',
  annual_capacity_tonnes: 300000,
  annual_production_tonnes: 280000,
  input_material: 'Copper-Gold Concentrate',
  output_material: 'Copper Cathode & Gold Dore',
  output_purity_percent: 99.99,
  workforce: 650,
  environmental_rating: 'B+',
  certifications: ['ISO 14001', 'ISO 45001', 'LME Approved'],
  dedicated_grasberg_processing: true,
  gold_processing_oz_year: 800000,
  silver_processing_oz_year: 3200000,
  ore_export_ban_compliance: true
});

// ==================== LITHIUM PROCESSORS ====================
// Convert spodumene ore and brine into lithium compounds

CREATE
// China - Tianqi Lithium (processes Greenbushes spodumene)
(processor_li_tianqi:Processor {
  id: 'PROC-LI-TIA',
  name: 'Tianqi Lithium Kwinana',
  country: 'Australia',
  region: 'Western Australia',
  coordinates: [-32.2167, 115.7833],
  owner: 'Tianqi Lithium',
  ownership_percent: 100,
  parent_company_country: 'China',
  operating_since: 2019,
  process_type: 'Lithium Hydroxide Production',
  technology: 'Sulfate roasting + purification',
  annual_capacity_lce_tonnes: 48000,
  annual_production_lce_tonnes: 45000,
  input_material: 'Lithium Spodumene Concentrate',
  output_material: 'Lithium Hydroxide Monohydrate',
  output_purity_percent: 99.5,
  battery_grade: true,
  workforce: 320,
  investment_usd_million: 700,
  certifications: ['ISO 14001', 'ISO 9001', 'IATF 16949'],
  customer_certifications: ['Tesla approved', 'CATL approved', 'LG Chem approved'],
  expansion_planned: true,
  expansion_capacity_lce_tonnes: 24000,
  expansion_timeline: '2025-2027',
  environmental_rating: 'A-',
  water_recycling_percent: 80,
  renewable_energy_target_percent: 100,
  renewable_energy_target_year: 2030
}),

// Chile - SQM Lithium (processes Salar de Atacama brine)
(processor_li_sqm:Processor {
  id: 'PROC-LI-SQM',
  name: 'SQM Salar del Carmen',
  country: 'Chile',
  region: 'Antofagasta',
  coordinates: [-23.6500, -70.4000],
  owner: 'SQM',
  ownership_percent: 100,
  major_shareholder: 'Tianqi Lithium 23.77%',
  operating_since: 1997,
  process_type: 'Brine processing + chemical conversion',
  technology: 'Evaporation + carbonation',
  annual_capacity_lce_tonnes: 180000,
  annual_production_lce_tonnes: 175000,
  input_material: 'Lithium Brine',
  output_products: ['Lithium Carbonate', 'Lithium Hydroxide', 'Potassium Chloride'],
  lithium_carbonate_capacity_tonnes: 120000,
  lithium_hydroxide_capacity_tonnes: 60000,
  output_purity_percent: 99.5,
  battery_grade_percent: 65,
  technical_grade_percent: 35,
  workforce: 2800,
  environmental_rating: 'C+',
  water_rights_controversy: true,
  water_extraction_limit_m3_hour: 442,
  regulatory_oversight: 'CORFO quota system',
  quota_expiry: 2030,
  certifications: ['ISO 14001', 'ISO 9001'],
  customer_base: ['Tesla', 'Samsung SDI', 'LG Energy Solution', 'CATL'],
  strategic_importance: 'World\'s 2nd largest lithium producer'
}),

// Chile - Albemarle (processes Salar de Atacama brine)
(processor_li_albemarle:Processor {
  id: 'PROC-LI-ALB',
  name: 'Albemarle La Negra',
  country: 'Chile',
  region: 'Antofagasta',
  coordinates: [-23.6667, -70.4000],
  owner: 'Albemarle Corporation',
  ownership_percent: 100,
  headquarters_country: 'USA',
  operating_since: 1984,
  process_type: 'Brine concentration + conversion',
  annual_capacity_lce_tonnes: 85000,
  annual_production_lce_tonnes: 80000,
  input_material: 'Lithium Brine from Salar de Atacama',
  output_material: 'Lithium Carbonate & Lithium Hydroxide',
  output_purity_percent: 99.5,
  battery_grade: true,
  workforce: 1400,
  environmental_rating: 'B',
  certifications: ['ISO 14001', 'ISO 45001', 'ISO 50001'],
  expansion_project: 'La Negra III & IV',
  expansion_investment_usd_million: 1300,
  expansion_capacity_add_lce_tonnes: 40000,
  sustainability_initiatives: ['Solar power', 'Water reduction', 'Biodiversity protection'],
  community_investment_usd_million_year: 8,
  indigenous_consultation: true
}),

// China - Ganfeng Lithium (processes Mt Marion spodumene)
(processor_li_ganfeng:Processor {
  id: 'PROC-LI-GAN',
  name: 'Ganfeng Lithium Jiangxi',
  country: 'China',
  region: 'Jiangxi Province',
  coordinates: [27.6333, 114.9167],
  owner: 'Ganfeng Lithium',
  ownership_type: 'Publicly listed',
  operating_since: 2002,
  process_type: 'Integrated lithium compound production',
  technology: 'Sulfate method + chlorination',
  annual_capacity_lce_tonnes: 100000,
  annual_production_lce_tonnes: 95000,
  input_materials: ['Spodumene concentrate', 'Lithium brine', 'Recycled lithium'],
  output_products: ['Lithium carbonate', 'Lithium hydroxide', 'Lithium metal', 'Lithium chloride'],
  battery_grade: true,
  workforce: 3200,
  certifications: ['ISO 14001', 'ISO 9001', 'IATF 16949'],
  vertical_integration: 'Mine to metal',
  recycling_capacity_tonnes_year: 10000,
  lithium_metal_production: true,
  lithium_metal_capacity_tonnes: 4500,
  strategic_partnerships: ['Tesla', 'BMW', 'VW', 'LG'],
  global_presence: ['Australia', 'Argentina', 'Ireland', 'Mexico'],
  market_position: 'World\'s largest lithium metal producer',
  environmental_rating: 'B'
});

// ==================== COBALT REFINERIES ====================
// Process cobalt-copper concentrates into pure cobalt compounds

CREATE
// Belgium - Umicore (world's largest cobalt refinery)
(refinery_co_umicore:Refinery {
  id: 'REF-CO-UMI',
  name: 'Umicore Hoboken',
  country: 'Belgium',
  region: 'Antwerp',
  coordinates: [51.1667, 4.3500],
  owner: 'Umicore',
  ownership_percent: 100,
  operating_since: 1889,
  cobalt_processing_since: 1960,
  process_type: 'Hydrometallurgical refining',
  technology: 'Solvent extraction + precipitation',
  annual_capacity_cobalt_tonnes: 45000,
  annual_production_cobalt_tonnes: 42000,
  input_material: 'Cobalt hydroxide & concentrates',
  output_products: ['Cobalt sulfate', 'Cobalt oxide', 'Cobalt metal'],
  cobalt_sulfate_purity_percent: 99.95,
  battery_grade: true,
  workforce: 1800,
  environmental_rating: 'A',
  ethical_rating: 'A',
  certifications: ['ISO 14001', 'ISO 45001', 'RBA', 'RMI'],
  blockchain_traceability: true,
  drc_material_percent: 65,
  audit_program: 'Independent third-party audits',
  child_labor_prevention: 'Comprehensive monitoring',
  responsible_sourcing_standard: 'OECD Due Diligence Guidance',
  precious_metals_recovery: true,
  metals_recovered: ['Gold', 'Silver', 'Platinum', 'Palladium', 'Rhodium', 'Indium', 'Germanium'],
  circular_economy_champion: true,
  recycling_capacity_tonnes_year: 15000,
  battery_recycling: true,
  strategic_importance: 'Europe\'s ethical cobalt supply',
  customer_approvals: ['Tesla', 'BMW', 'VW', 'Panasonic', 'Samsung']
}),

// China - Zhejiang Huayou Cobalt
(refinery_co_huayou:Refinery {
  id: 'REF-CO-HUA',
  name: 'Zhejiang Huayou Cobalt',
  country: 'China',
  region: 'Zhejiang Province',
  coordinates: [29.7167, 120.7500],
  owner: 'Huayou Cobalt',
  ownership_type: 'Publicly listed',
  operating_since: 2002,
  process_type: 'Hydrometallurgical processing',
  annual_capacity_cobalt_tonnes: 80000,
  annual_production_cobalt_tonnes: 75000,
  input_material: 'Cobalt concentrates & intermediates',
  output_products: ['Cobalt sulfate', 'Cobalt oxide', 'Cobalt metal powder'],
  battery_grade: true,
  workforce: 4500,
  environmental_rating: 'B+',
  ethical_rating: 'B',
  certifications: ['ISO 14001', 'ISO 9001', 'RMI'],
  drc_sourcing: true,
  audit_frequency_year: 4,
  traceability_system: 'Digital tracking',
  vertical_integration: 'Mine ownership in DRC',
  drc_mines_operated: ['Mikas', 'KFM'],
  expansion_africa: true,
  market_position: 'World\'s largest cobalt chemicals producer',
  customer_base: ['CATL', 'BYD', 'EVE', 'Farasis'],
  precursor_production: true,
  precursor_capacity_tonnes_year: 120000
}),

// Finland - Terrafame (ethical EU source)
(refinery_co_terrafame:Refinery {
  id: 'REF-CO-TER',
  name: 'Terrafame Sotkamo',
  country: 'Finland',
  region: 'Kainuu',
  coordinates: [64.1333, 28.3833],
  owner: 'Terrafame Ltd',
  ownership_percent: 100,
  government_ownership: 'Finnish state majority owner',
  operating_since: 2008,
  cobalt_production_since: 2021,
  process_type: 'Bioheapleaching + hydrometallurgy',
  technology: 'Bacterial leaching (unique)',
  annual_capacity_nickel_tonnes: 35000,
  annual_capacity_cobalt_tonnes: 6000,
  annual_production_cobalt_tonnes: 5500,
  input_material: 'Nickel-cobalt ore',
  output_products: ['Nickel sulfate', 'Cobalt sulfate'],
  battery_grade: true,
  workforce: 780,
  environmental_rating: 'A-',
  ethical_rating: 'A+',
  conflict_free: true,
  certifications: ['ISO 14001', 'ISO 45001', 'RBA'],
  european_battery_alliance_member: true,
  strategic_importance: 'Only EU battery metals producer',
  sustainability_highlights: ['No child labor', 'Low carbon footprint', 'Circular economy'],
  premium_pricing: true,
  premium_justification: 'Conflict-free European origin',
  customers: ['BASF', 'European cathode producers'],
  expansion_planned: 2027,
  expansion_investment_eur_million: 450
});

// ==================== RARE EARTH ELEMENT PROCESSORS ====================
// Separate and refine rare earth concentrates into individual elements

CREATE
// China - Baotou Steel Rare Earth (processes Bayan Obo ore)
(processor_ree_baotou:Processor {
  id: 'PROC-REE-BAO',
  name: 'Baotou Steel Rare Earth',
  country: 'China',
  region: 'Inner Mongolia',
  coordinates: [40.6522, 109.8222],
  owner: 'China Northern Rare Earth Group',
  ownership_type: 'State-owned enterprise',
  operating_since: 1961,
  process_type: 'Separation & refining',
  technology: 'Solvent extraction cascade',
  annual_capacity_ree_tonnes: 100000,
  annual_production_ree_tonnes: 95000,
  input_material: 'Rare earth concentrate from Bayan Obo',
  output_products: ['Neodymium oxide', 'Praseodymium oxide', 'Dysprosium oxide', 'Terbium oxide', 'Cerium oxide', 'Lanthanum oxide'],
  purity_percent: 99.5,
  workforce: 5200,
  environmental_rating: 'D',
  environmental_concerns: ['Radioactive waste', 'Toxic chemical discharge', 'Air pollution'],
  wastewater_treatment: 'Limited',
  radioactive_tailings_pond_hectares: 11,
  certifications: ['ISO 9001'],
  strategic_resource: true,
  export_restrictions: 'Subject to quotas',
  domestic_priority: 'EV motors & wind turbines',
  market_dominance_percent: 70,
  monopoly_concerns: true,
  geopolitical_leverage: 'Critical for global tech supply'
}),

// Malaysia - Lynas (processes Australian concentrate)
(processor_ree_lynas:Processor {
  id: 'PROC-REE-LYN',
  name: 'Lynas Advanced Materials Plant',
  country: 'Malaysia',
  region: 'Kuantan, Pahang',
  coordinates: [3.8167, 103.3167],
  owner: 'Lynas Rare Earths',
  ownership_percent: 100,
  headquarters_country: 'Australia',
  operating_since: 2013,
  process_type: 'Solvent extraction & separation',
  technology: 'Counter-current extraction',
  annual_capacity_ree_tonnes: 22000,
  annual_production_ree_tonnes: 20000,
  input_material: 'Rare earth concentrate from Mt Weld, Australia',
  output_products: ['Neodymium-Praseodymium', 'Lanthanum', 'Cerium', 'SEG/HRE'],
  purity_percent: 99.5,
  workforce: 850,
  environmental_rating: 'B+',
  certifications: ['ISO 14001', 'ISO 45001', 'ISO 9001'],
  controversy: 'Initial local opposition',
  regulatory_compliance: 'Strict Malaysian standards',
  water_treatment: 'Advanced',
  waste_management: 'Permanent disposal facility',
  strategic_importance: 'Largest non-Chinese REE processor',
  pentagon_interest: true,
  us_government_funding: 'Development contracts',
  expansion_us: 'Heavy rare earths facility Texas',
  expansion_australia: 'Kalgoorlie refinery',
  customer_base: ['Automotive OEMs', 'Wind turbine makers', 'Electronics'],
  market_position: 'Only significant China alternative'
}),

// USA - MP Materials (under construction)
(processor_ree_mp:Processor {
  id: 'PROC-REE-MP',
  name: 'MP Materials Mountain Pass',
  country: 'USA',
  region: 'California',
  coordinates: [35.4800, -115.5300],
  owner: 'MP Materials',
  ownership_percent: 100,
  operating_since: 2020,
  separation_facility_status: 'Under construction',
  expected_completion: 2025,
  process_type: 'Integrated mining to magnet production',
  technology: 'Solvent extraction',
  planned_capacity_ree_tonnes: 40000,
  input_material: 'Bastnaesite concentrate (on-site mine)',
  output_products_planned: ['Neodymium oxide', 'Praseodymium oxide', 'Dysprosium oxide'],
  target_purity_percent: 99.9,
  workforce_planned: 350,
  investment_usd_million: 700,
  environmental_rating: 'A-',
  certifications_planned: ['ISO 14001', 'ISO 45001', 'ISO 9001'],
  strategic_importance: 'End US dependence on China',
  pentagon_funding: true,
  dod_contracts: 'Heavy rare earth processing',
  current_limitation: 'Concentrate exported to China for separation',
  goal: 'Full domestic supply chain by 2025',
  magnet_manufacturing_planned: true,
  vertical_integration_target: 'Mine to magnet',
  customers_committed: ['GM', 'Raytheon'],
  national_security_designation: true
});

// Success message
MATCH (n)
WHERE n:Smelter OR n:Refinery OR n:Processor
RETURN 'Part 2 Complete: Created ' + count(n) + ' processor/refinery/smelter nodes with rich detail' as message;
